# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\match\embeded\25\src\PrimeCiallo\CountDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_countDialog(object):
    def setupUi(self, countDialog):
        countDialog.setObjectName("countDialog")
        countDialog.setEnabled(True)
        countDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(countDialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 220, 191, 41))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.setcountspinBox = QtWidgets.QSpinBox(countDialog)
        self.setcountspinBox.setGeometry(QtCore.QRect(110, 90, 171, 91))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.setcountspinBox.setFont(font)
        self.setcountspinBox.setMaximum(200)
        self.setcountspinBox.setSingleStep(1)
        self.setcountspinBox.setProperty("value", 6)
        self.setcountspinBox.setDisplayIntegerBase(10)
        self.setcountspinBox.setObjectName("setcountspinBox")
        self.label = QtWidgets.QLabel(countDialog)
        self.label.setGeometry(QtCore.QRect(50, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(countDialog)
        QtCore.QMetaObject.connectSlotsByName(countDialog)

    def retranslateUi(self, countDialog):
        _translate = QtCore.QCoreApplication.translate
        countDialog.setWindowTitle(_translate("countDialog", "CountDialog"))
        self.label.setText(_translate("countDialog", "设置计数"))
