# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\match\embeded\25\src\PrimeCiallo\TimerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_timerDialog(object):
    def setupUi(self, timerDialog):
        timerDialog.setObjectName("timerDialog")
        timerDialog.resize(400, 300)
        self.settimeEdit = QtWidgets.QTimeEdit(timerDialog)
        self.settimeEdit.setGeometry(QtCore.QRect(50, 90, 291, 91))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(28)
        self.settimeEdit.setFont(font)
        self.settimeEdit.setTime(QtCore.QTime(0, 0, 15))
        self.settimeEdit.setObjectName("settimeEdit")
        self.label = QtWidgets.QLabel(timerDialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(timerDialog)
        self.buttonBox.setGeometry(QtCore.QRect(90, 230, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(timerDialog)
        QtCore.QMetaObject.connectSlotsByName(timerDialog)

    def retranslateUi(self, timerDialog):
        _translate = QtCore.QCoreApplication.translate
        timerDialog.setWindowTitle(_translate("timerDialog", "TimerDialog"))
        self.settimeEdit.setDisplayFormat(_translate("timerDialog", "mm:ss"))
        self.label.setText(_translate("timerDialog", "设置时长"))
